global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/alerting-rules.yaml

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "storage-sage"
    static_configs:
      - targets: ["storage-sage:9090"]
    scrape_interval: 10s
